### ISSUE TITLE
大神能不能提供一个点开即用的OneDrive图床配置工具呀😶‍🌫️

### ISSUE THREAD

**Issue by jierme** [harrisoff/onedrive-api#1]
我是小白一位，医学研究生，喜欢使用Typoia为文献写一些批注，发现免费图床不稳定，既往做的笔记很多图片已经打不开了，想折腾一下，用自己的OneDrive作图床，但是我只自学过Python，只会一点点皮毛，跟着大神提供的说明和OneDrive的官方文档读了好久还是没有折腾好，要是大神有空的话，能不能写一个点开即用的OneDrive图床配置工具呀 (つД`)ノ，要是能是python写的就更好啦。

冒昧打扰，还请大神谅解～
要是大神没空也没关系的，closed就好了～

祝好！

**Comment by harrisoff** [comment]
typora 最好的方案应该是 picgo，图床有很多选择，可以上传到 github 或者七牛云之类的，都是自己账号下的空间，不会有免费图床一样的问题

onedrive 因为不提供永久的 access token，只能每次用的时候去申请 & 过期的时候手动刷新，这部分逻辑又要写代码又要部署项目，还要想办法集成到 typora。。就很麻烦了
